### ISSUE TITLE
use with paper-scroll-header panel

### ISSUE THREAD

**Issue by NicolasRannou** [winhowes/parallax-container#7]
Is it possible to use it with paper-scroll-header-panel?
https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-1.html&active=paper-scroll-header-panel

I am having to hook up things properly.

Thanks

**Comment by NicolasRannou** [comment]
https://fnndsc.babymri.org/#!/fnndsc-overview

**Comment by winhowes** [comment]
Sorry for the delay - took me some time to figure this one out and come up with what I think is a reasonable solution. So the `parallax-container` now emits its `scrollTop` value through the `scroll-top-value-changed` event (info in docs).

Because `paper-scroll-header-panel` is a little funky with how they do scrolling what you can now do is add an event listener and set the `scrollTop` of the `#mainContainer` inside of `paper-scroll-header-panel` to the `scrollTop` of the `parallax-container`. It looks like this:

```js
document.getElementsByTagName('parallax-container')[0].addEventListener('scroll-top-value-changed', function(e) {
    document.getElementById('mainContainer').scrollTop = e.detail.value;
});
```

Let me know if I can clarify further! There may be some tweaking you have to do, but I thought this would be the most general solution to the issue and give the developer the most flexibility. Hope it helps!

**Comment by NicolasRannou** [comment]
Awesome! Thanks I'll give it a try!
